export const AppConfig = {
  site_name: 'Kevin Barbershop',
  title: 'Kevin Barbershop | Book Online',
  description: 'Kevin Barbershop website with online appointment scheduling.',
  locale: 'en',
  shopTimeZone: 'America/Los_Angeles',
  shopTimeLabel: 'PT',
  shopPhoneDisplay: '(555) 123-4567',
  shopPhoneE164: '+15551234567',
  legalBusinessName: 'Kevin Barbershop LLC',
  legalAddress: '123 Main St, Los Angeles, CA 90001, United States',
  supportEmail: 'support@kevinbarbershop.com',
  privacyEmail: 'privacy@kevinbarbershop.com',
  accessibilityEmail: 'accessibility@kevinbarbershop.com',
  legalVersion: '2026-02-12',
  cancellationCutoffHours: 2,
};
